### ISSUE TITLE
ClassNotFound exception for InMemoryDataSource

### ISSUE THREAD

**Issue by santbob** [babylonhealth/certificate-transparency-android#15]
I am trying to use the this module in an java based Android SDK and it comes back with this error.

I did add the dependencies in the `build.gradle`, am i missing any other dependencies?
```
implementation 'com.babylon.certificatetransparency:certificatetransparency:0.1.2'
implementation "org.jetbrains.kotlin:kotlin-stdlib:1.3.31"
```
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/babylon/certificatetransparency/internal/loglist/InMemoryDataSource;
        at com.babylon.certificatetransparency.internal.verifier.CertificateTransparencyBase.<init>(CertificateTransparencyBase.kt:58)
        at com.babylon.certificatetransparency.internal.verifier.CertificateTransparencyBase.<init>(CertificateTransparencyBase.kt:44)
        at com.babylon.certificatetransparency.internal.verifier.CertificateTransparencyInterceptor.<init>(CertificateTransparencyInterceptor.kt:37)
        at com.babylon.certificatetransparency.CTInterceptorBuilder.build(CTInterceptorBuilder.kt:144)
```

**Comment by mattmook** [comment]
Hi there, did you figure out what was happening as we haven't seen this ourselves?

Does the same thing happen with the latest release v0.1.4? Is ProGuard enabled?

If you are able to provide a sample app that exhibits this behaviour that can really help too.

**Comment by santbob** [comment]
I tried the latest version then. Yes its progaurd enabled but the crash happened on the debug build where the progaurd doesn't kick in.

As of now working on other priorities, i will post a sample when i can get to it.

Thanks for the response.
