### ISSUE TITLE
Crash when R8 is enabled

### ISSUE THREAD

**Issue by VysotskiVadim** [babylonhealth/certificate-transparency-android#38]
Enabling R8 causes crash 
```
Fatal Exception: java.lang.RuntimeException: Unable to invoke no-args constructor for class c1.c.a.h.c.u.a.b. Registering an InstanceCreator with Gson for this type may fix this problem.
       at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:32)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.a(ReflectiveTypeAdapterFactory.java:15)
       at com.google.gson.Gson.fromJson(Gson.java:5)
       at com.google.gson.Gson.fromJson(Gson.java:14)
       at com.google.gson.Gson.fromJson(Gson.java:3)
       at com.babylon.certificatetransparency.internal.loglist.parser.LogListJsonParserV2.parseJson(LogListJsonParserV2.java:3)
       at com.babylon.certificatetransparency.internal.loglist.parser.RawLogListToLogListResultTransformer.transformSuccess(RawLogListToLogListResultTransformer.java:3)
       at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory$create$2.invoke(LogListDataSourceFactory.java:1)
```
Crash can be fixed by adding following to project's `proguard-rules.pro` file
```
-keep class com.babylon.certificatetransparency.internal.loglist.model.v2.** { *; }
```

**Comment by mattmook** [comment]
Thanks for the report I've updated the consumer proguard rules to include this entry. This will be added to the next release.
