### ISSUE TITLE
How to create one separate “jar” or “aar” by this CTL project ?

### ISSUE THREAD

**Issue by RobbieZhu** [babylonhealth/certificate-transparency-android#64]
**After compiling this project source code into jar and AAR library, we encountered a runtime error as shown in the figure below. How should we handle it? Thank you!**

D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pra.jyao20.ctl3, PID: 29195
    java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit2/Retrofit$Builder;
        at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory.create(LogListDataSourceFactory.kt:34)
        at com.babylon.certificatetransparency.internal.verifier.CertificateTransparencyBase.<init>(CertificateTransparencyBase.kt:69)
        at com.babylon.certificatetransparency.internal.verifier.CertificateTransparencyInterceptor.<init>(CertificateTransparencyInterceptor.kt:44)
        at com.babylon.certificatetransparency.CTInterceptorBuilder.build(CTInterceptorBuilder.kt:231)
        at pra.jyao20.ctl3.MainActivity.addCt(MainActivity.kt:94)
        at pra.jyao20.ctl3.MainActivity.okHttpRequest(MainActivity.kt:46)
        at pra.jyao20.ctl3.MainActivity.access$okHttpRequest(MainActivity.kt:18)
        at pra.jyao20.ctl3.MainActivity$onCreate$2.onClick(MainActivity.kt:32)
        at android.view.View.performClick(View.java:7250)
        at android.view.View.performClickInternal(View.java:7227)
        at android.view.View.access$3500(View.java:819)
        at android.view.View$PerformClick.run(View.java:27749)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "retrofit2.Retrofit$Builder" on path: DexPathList[[zip file "/data/app/pra.jyao20.ctl3-utW69wtJypMQlPcmdrdHkw==/base.apk"],nativeLibraryDirectories=[/data/app/pra.jyao20.ctl3-utW69wtJypMQlPcmdrdHkw==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory.create(LogListDataSourceFactory.kt:34) 
        at com.babylon.certificatetransparency.internal.verifier.CertificateTransparencyBase.<init>(CertificateTransparencyBase.kt:69) 
        at com.babylon.certificatetransparency.internal.verifier.CertificateTransparencyInterceptor.<init>(CertificateTransparencyInterceptor.kt:44) 
        at com.babylon.certificatetransparency.CTInterceptorBuilder.build(CTInterceptorBuilder.kt:231) 
        at pra.jyao20.ctl3.MainActivity.addCt(MainActivity.kt:94) 
        at pra.jyao20.ctl3.MainActivity.okHttpRequest(MainActivity.kt:46) 
        at pra.jyao20.ctl3.MainActivity.access$okHttpRequest(MainActivity.kt:18) 
        at pra.jyao20.ctl3.MainActivity$onCreate$2.onClick(MainActivity.kt:32) 
        at android.view.View.performClick(View.java:7250) 
        at android.view.View.performClickInternal(View.java:7227) 
        at android.view.View.access$3500(View.java:819) 
        at android.view.View$PerformClick.run(View.java:27749) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7562) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
E/MQSEventManagerDelegate: failed to get MQSService.
I/Process: Sending signal. PID: 29195 SIG: 9

**Comment by mattmook** [comment]
Hi @RobbieZhu, based off the above, it sounds like you're not including transitive dependencies in your project so don't have Retrofit on the classpath.

Generally it would be preferred to include the library through gradle, or indeed maven which should also work although not test.

Otherwise, the only other thing I can suggest is to configure the project to generate a fatJar to include all its dependencies, but this can be much more problematic if your project contains any of the same dependencies as it will complain about duplicate classes instead.
