### ISSUE TITLE
java.security.NoSuchAlgorithmException: SHA-256 MessageDigest not available

### ISSUE THREAD

**Issue by darwind** [babylonhealth/certificate-transparency-android#71]
We're seeing a few of these exceptions in Crashlytics in our app:

```
Caused by java.security.NoSuchAlgorithmException: SHA-256 MessageDigest not available
       at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
       at java.security.Security.getImpl(Security.java:628)
       at java.security.MessageDigest.getInstance(MessageDigest.java:197)
       at com.babylon.certificatetransparency.internal.utils.PublicKeyExtKt.sha256Hash(PublicKeyExtKt.java:26)
       at com.babylon.certificatetransparency.loglist.LogServer.<init>(LogServer.java:34)
       at com.babylon.certificatetransparency.internal.loglist.parser.LogListJsonParserV2.buildLogServerList(LogListJsonParserV2.java:67)
       at com.babylon.certificatetransparency.internal.loglist.parser.LogListJsonParserV2.parseJson(LogListJsonParserV2.java:41)
       at com.babylon.certificatetransparency.internal.loglist.parser.RawLogListToLogListResultTransformer.transformSuccess(RawLogListToLogListResultTransformer.java:51)
       at com.babylon.certificatetransparency.internal.loglist.parser.RawLogListToLogListResultTransformer.transform(RawLogListToLogListResultTransformer.java:35)
       at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory$create$2.invoke(LogListDataSourceFactory.java:49)
       at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory$create$2.invoke(LogListDataSourceFactory.java:29)
       at com.babylon.certificatetransparency.datasource.DataSource$oneWayTransform$1.get(DataSource.java:113)
       at com.babylon.certificatetransparency.datasource.DataSource$reuseInflight$1$get$2.invokeSuspend(DataSource.java:86)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

It's been reported from different devices and different OS versions, but most devices are running Android 10.

We're using the CT library together with Retrofit and OkHttpClient.

**Comment by mattmook** [comment]
Hi @darwind,

What manufacturers do you see this across?

According to the [docs](https://developer.android.com/reference/java/security/MessageDigest) SHA-256 should be supported across all Android OS versions (since API 1).

Throwing random thoughts out there, do you use any JNI in your app? https://stackoverflow.com/questions/17877419/android-messagedigest-nosuchalgorithmexception-after-calling-jni-function

**Comment by darwind** [comment]
> Hi @darwind,
> 
> What manufacturers do you see this across?
> 
> According to the [docs](https://developer.android.com/reference/java/security/MessageDigest) SHA-256 should be supported across all Android OS versions (since API 1).
> 
> Throwing random thoughts out there, do you use any JNI in your app? https://stackoverflow.com/questions/17877419/android-messagedigest-nosuchalgorithmexception-after-calling-jni-function

Thanks for getting back to me.

Yes I would also expect all devices to support SHA-256, unless the manufacturers mess up something of course.

We see this on:
Huawei (P30 lite, P20 Pro, P smart 2019, Mate 9 Pro and P20 Lite)
Samsung (Galaxy S9 and Galaxy A41)
OnePlus (6T)

However we've only seen roughly 10 crashes with 10 different users, but with a userbase of roughly 300.000 users on Android it's not affecting a lot of users obviously.

I went digging through our 3rd party libraries and we're actually using an OCR engine, which is a proprietary library so I don't have access to the source code apart from the obfuscated code and this OCR engine is actually using RenderScript, so yes indirectly we're using JNI I suppose :-) The OCR engine is initialised inside our Application class as the first thing we're doing and then the first call to our backend is made a little later when the user presses a button, so I guess this could actually be the issue.

I don't have access to any of the users that experience this issue so it's gonna be hard to test out whether changing the call order will fix this issue of course.

**Comment by mattmook** [comment]
I can put a workaround in by having a fallback implementation of SHA-256, however, I am concerned it's just going to shift the problem elsewhere in the code.

As you say hard to know if it is the OCR library causing the issues... seems other Android libraries have experienced the same issues with no real resolution :/ [Mixpanel](https://github.com/mixpanel/mixpanel-android/issues/95) [Amplitude-Android](https://github.com/amplitude/Amplitude-Android/issues/3)

**Comment by mattmook** [comment]
Next release will use SHA256 directly from BC rather than through MessageDigest so the above exception can no longer occur. I guess we'll have to see whether there are any further unexplained exceptions further down the line
