### ISSUE TITLE
ClassNotFoundException when trying to use the builder or DSL funtion to build the interceptor 

### ISSUE THREAD

**Issue by Jitendra194** [babylonhealth/certificate-transparency-android#75]
I added **implementation "com.babylon.certificatetransparency:certificatetransparency-android:0.3.0"** as the dependency
and in the OkHttpClient I made sure to add **new CTInterceptorBuilder().includeHost("*.example.com").build()** as a network interceptor.

but this is the error that I see,

```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/babylon/certificatetransparency/CTInterceptorBuilderExtKt;
        
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.babylon.certificatetransparency.CTInterceptorBuilderExtKt" on path: DexPathList[[zip file]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 60 more
```

**Comment by mattmook** [comment]
Can I ask if this is on a debug or release build of the app? Just wondering if ProGuard/R8 is causing issues as I'm unable to reproduce.

Could you also try performing a `./gradlew clean build` to see if that rectifies the issue.

Failing that with these types of issues it can be worth invaliding the Android Studio cache:
 
<img width="283" alt="image" src="https://user-images.githubusercontent.com/182422/108856825-5c81c800-75e2-11eb-87f9-7f8e8ac6d266.png">

Other things that can be cleaned out can be found in [Android Studio is “Borked” — my checklist for fixing build issues
](https://medium.com/google-developer-experts/android-studio-is-borked-my-checklist-for-fixing-build-issues-e41a9dd8cba8)
